---
logs:
  - name: root
    level: info
    formatter: '%d%T%m%n'
    appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender
  - name: system
    level: debug
    formatter: '%d%T%m%n'
    appender:
      - type: FileLogAppender
        path: log.txt
      - type: StdoutLogAppender

system:
    port: 9900
    value: 15
    int_vec:
      - 10
      - 30
    int_list:
      - 10
      - 30
      - 40
    int_set:
      - 20
      - 40
      - 60
    int_unordered_set:
      - 20
      - 40
      - 60
    str_int_map:
      k: 30
      k2: 40
      k3: 50
    str_int_unordered_map:
      k: 20
      k2: 30
      k3: 40

class:
  person:
    name: Ryan
    age: 25
    sex: true
  map:
    user01:
      name: Ryan
      age: 20
      sex: false
    user02:
      name: Ryan2
      age: 30
      sex: false
  vec_map:
    k1:
      - name: m1
        age: 33
        sex: true
      - name: m2
        age: 44
        sex: false
    k2:
      - name: m21
        age: 33
        sex: true
      - name: m222
        age: 44
        sex: false
